import { StyleWorldPreset } from '../types';

export const STYLE_WORLD_PRESETS: StyleWorldPreset[] = [
  // ── Visionary / Complex ────────────────────────────────────────────────
  {
    id: 'bioluminescent',
    label: 'Bioluminescent',
    emoji: '✨',
    tagline: 'Living light from within',
    description: 'A living luminous world glowing from within, mystical and alive.',
    visualKeywords: ['internal glow', 'luminous tendrils', 'fractal light', 'pulse'],
    materialKeywords: ['glowing moss', 'luminous fungi', 'bioluminescent skin', 'light filaments'],
    atmosphereKeywords: ['mystical', 'alive', 'magical', 'deep darkness', 'extreme contrast'],
    colorKeywords: ['deep neon blue', 'electric purple', 'electric green', 'cyan core'],
  },
  {
    id: 'sacred-geometry',
    label: 'Sacred Geometry',
    emoji: '🔯',
    tagline: 'Mathematical structure made visible',
    description: 'A world built from intricate geometric systems and flowing mathematical structures.',
    visualKeywords: ['Metatron cube', 'seed of life', 'sacred symmetry', 'recursive structure'],
    materialKeywords: ['glowing lines', 'geometric surface', 'crystalline grid', 'pattern skin'],
    atmosphereKeywords: ['ordered', 'cosmic', 'mathematical', 'psychedelic'],
    colorKeywords: ['glowing cyan', 'magenta lines', 'gold outlines', 'deep black'],
  },
  {
    id: 'kaleidoscopic',
    label: 'Kaleidoscopic',
    emoji: '🌀',
    tagline: 'Infinite symmetry and mandala depth',
    description: 'Layered mandalas, kaleidoscopic symmetry, tapestry-like complexity and psychedelic depth.',
    visualKeywords: ['radial symmetry', 'intricate mandalas', 'patterned planes', 'tapestry'],
    materialKeywords: ['textile-like', 'patterned skin', 'geometric ornament', 'woven surface'],
    atmosphereKeywords: ['visionary', 'intense', 'decorative', 'complex depth'],
    colorKeywords: ['deep red', 'orange', 'gold', 'electric accents', 'dark background'],
  },
  {
    id: 'deep-dream',
    label: 'Deep Dream',
    emoji: '👁️',
    tagline: 'Surreal recursive hallucination',
    description: 'A surreal recursive world where forms transform into impossible beings, eyes, and organic hallucinations.',
    visualKeywords: ['recursive forms', 'surreal eyes', 'impossible animals', 'morphing'],
    materialKeywords: ['organic texture', 'dream-like surface', 'layered hallucination', 'creature skin'],
    atmosphereKeywords: ['unstable', 'surreal', 'hallucinatory', 'intense', 'dark contrast'],
    colorKeywords: ['intense multicolor', 'deep darks', 'vivid accent', 'iridescent'],
  },
  {
    id: 'visionary',
    label: 'Visionary',
    emoji: '🌌',
    tagline: 'Transcendental spiritual energy',
    description: 'A visionary transcendental world with energetic anatomical and mystical systems.',
    visualKeywords: ['energy channels', 'luminous internal systems', 'eye fields', 'sacred symmetry'],
    materialKeywords: ['spiritual skin', 'glowing anatomy', 'etheric body', 'light structure'],
    atmosphereKeywords: ['transcendental', 'sacred', 'cosmic', 'ethereal', 'profound'],
    colorKeywords: ['deep blue', 'gold', 'violet', 'inner light', 'cosmic glow'],
  },
  // ── Nature / World ────────────────────────────────────────────────────
  {
    id: 'forest',
    label: 'Forest',
    emoji: '🌿',
    tagline: 'Bark, roots, moss and mist',
    description: 'A forest spirit world — bark, roots, glowing moss, woodland mist.',
    visualKeywords: ['bark texture', 'root structure', 'forest mist', 'woodland canopy'],
    materialKeywords: ['bark skin', 'moss surface', 'root limbs', 'fungi glow'],
    atmosphereKeywords: ['misty', 'ancient', 'organic', 'wild'],
    colorKeywords: ['deep green', 'earth brown', 'golden light', 'moss glow'],
  },
  {
    id: 'sea',
    label: 'Sea',
    emoji: '🌊',
    tagline: 'Coral, water and deep ocean glow',
    description: 'An oceanic world — coral, shells, bioluminescence, underwater depth.',
    visualKeywords: ['caustic light', 'underwater haze', 'coral forms', 'wave motion'],
    materialKeywords: ['coral skin', 'shell armor', 'algae surface', 'wet translucent'],
    atmosphereKeywords: ['deep', 'fluid', 'aquatic', 'ethereal'],
    colorKeywords: ['ocean blue', 'teal glow', 'pearl white', 'deep navy'],
  },
  {
    id: 'fire',
    label: 'Fire',
    emoji: '🔥',
    tagline: 'Flame, ember and molten heat',
    description: 'A fire world — flame beings, molten surfaces, heat shimmer, ember glow.',
    visualKeywords: ['flame forms', 'ember sparks', 'heat shimmer', 'smoke trails'],
    materialKeywords: ['lava skin', 'ember texture', 'cracked heat surface', 'molten core'],
    atmosphereKeywords: ['intense', 'hot', 'dramatic', 'dangerous'],
    colorKeywords: ['deep black', 'orange glow', 'yellow white', 'ember red'],
  },
  {
    id: 'spirit',
    label: 'Spirit',
    emoji: '👻',
    tagline: 'Ethereal, ghostly and cold glow',
    description: 'A spirit world — translucent forms, cold glow, drifting smoke.',
    visualKeywords: ['smoke edges', 'spectral light', 'drifting energy', 'cold mist'],
    materialKeywords: ['translucent skin', 'smoke body', 'spectral surface', 'wind form'],
    atmosphereKeywords: ['haunted', 'cold', 'ethereal', 'eerie'],
    colorKeywords: ['cold blue', 'pale violet', 'ghost white', 'deep dark'],
  },
  {
    id: 'cartoon',
    label: 'Cartoon',
    emoji: '🎨',
    tagline: 'Bold illustration and vivid stylization',
    description: 'A cartoon world — bold shapes, vivid colors, expressive illustration.',
    visualKeywords: ['bold outlines', 'stylized shading', 'expressive lines', 'cartoon shapes'],
    materialKeywords: ['flat color surface', 'stylized texture', 'illustrated form', 'bold design'],
    atmosphereKeywords: ['playful', 'vivid', 'expressive', 'energetic'],
    colorKeywords: ['vivid primary', 'bold accent', 'high saturation', 'black outline'],
  },
  {
    id: 'ice',
    label: 'Ice',
    emoji: '❄️',
    tagline: 'Frost, crystal and pale cold light',
    description: 'An ice world — frozen surfaces, crystalline frost, cold pale light.',
    visualKeywords: ['frost patterns', 'ice crystals', 'frozen surface', 'cold sparkle'],
    materialKeywords: ['ice skin', 'frost texture', 'crystalline form', 'frozen armor'],
    atmosphereKeywords: ['cold', 'still', 'pristine', 'sharp'],
    colorKeywords: ['pale blue', 'ice white', 'cold cyan', 'frost silver'],
  },
  {
    id: 'crystal',
    label: 'Crystal',
    emoji: '💎',
    tagline: 'Prismatic, rainbow and refractive',
    description: 'A crystal world — prismatic refraction, rainbow light, gem-like surfaces.',
    visualKeywords: ['prismatic split', 'rainbow refraction', 'gem facets', 'light dispersion'],
    materialKeywords: ['crystal skin', 'gem surface', 'refractive body', 'prismatic form'],
    atmosphereKeywords: ['magical', 'brilliant', 'otherworldly', 'radiant'],
    colorKeywords: ['rainbow spectrum', 'deep violet', 'prismatic white', 'electric accent'],
  },
  {
    id: 'shadow',
    label: 'Shadow',
    emoji: '🌑',
    tagline: 'Dark, purple, high contrast',
    description: 'A shadow world — extreme darkness, violet highlights, high contrast silhouette.',
    visualKeywords: ['deep shadow', 'violet edge', 'high contrast silhouette', 'dark form'],
    materialKeywords: ['shadow skin', 'void texture', 'dark energy surface', 'ethereal black'],
    atmosphereKeywords: ['ominous', 'mysterious', 'powerful', 'dark'],
    colorKeywords: ['near black', 'deep purple', 'violet glow', 'dark indigo'],
  },
  {
    id: 'floral',
    label: 'Floral',
    emoji: '🌸',
    tagline: 'Bloom, petal and dreamy soft light',
    description: 'A floral world — petal surfaces, bloom glow, soft dreamlike atmosphere.',
    visualKeywords: ['petal forms', 'bloom glow', 'floral patterns', 'soft light'],
    materialKeywords: ['petal skin', 'flower surface', 'organic bloom texture', 'soft form'],
    atmosphereKeywords: ['dreamy', 'soft', 'delicate', 'romantic'],
    colorKeywords: ['soft pink', 'warm magenta', 'pale gold', 'blush white'],
  },
  {
    id: 'machine',
    label: 'Machine',
    emoji: '⚙️',
    tagline: 'Green terminal, metal and grid',
    description: 'A machine world — metallic surfaces, terminal green, hard-edged grid logic.',
    visualKeywords: ['circuit grid', 'terminal lines', 'mechanical form', 'gear structure'],
    materialKeywords: ['metal skin', 'circuit texture', 'gear surface', 'hard edge form'],
    atmosphereKeywords: ['cold', 'mechanical', 'precise', 'industrial'],
    colorKeywords: ['terminal green', 'dark metal', 'phosphor glow', 'grid lines'],
  },
];

export const PRESET_MAP = Object.fromEntries(
  STYLE_WORLD_PRESETS.map((p) => [p.id, p])
) as Record<string, StyleWorldPreset>;
